baseUrl: http://192.168.0.3
title: Tori Writes Online
copyright: MIT
paginate: 3
languageCode: en
defaultContentLanguage: en
enableInlineShortcodes: true
theme: hugo-theme-willow
pluralizelisttitles: false
#canonifyURLs: true
author: 
  name: Victoria Rodriguez

params:
  env: development
  description: Personal blog and portfolio
  subtitle: Programmer | Writer | Devoted Web Geek
  avatar: avatar.svg
  homeMessage: Welcome
  googleFonts: https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,400;0,700;1,400;1,700&display=swap
  contact:
    - name: E-mail
      icon: fas fa-envelope
      url: mailto:vrodriguezfe@icloud.com
      hoverColor: grey-dark
    - name: Github
      icon: fab fa-github-alt
      url: https://github.com/nerdalot
      hoverColor: purple-dark
    - name: Spotify
      icon: fab fa-spotify
      url: https://open.spotify.com/user/malditoprotozoo
      hoverColor: green-dark
    - name: Telegram
      icon: fab fa-telegram-plane
      url: https://t.me/nerdalot
      hoverColor: cyan-dark
    - name: Twitter
      icon: fab fa-twitter
      url: https://twitter.com/nerdalot
      hoverColor: cyan
    - name: Youtube
      icon: fab fa-youtube
      url: https://youtube.com/c/UCoACZSKfzZcl2fDT1ybaRwAr
      hoverColor: red-dark
  debug:
    enabled: false

taxonomies:
  - category: categories
  - tag: tags
  - serie: series