main:
  - identifier: home
    name: Home
    url: /
    pre: home.svg
    weight: 1
  - identifier: about
    name: About
    url: about
    pre: about.svg
    weight: 2
  - identifier: projects
    name: Projects
    url: projects
    pre: projects.svg
    weight: 3
  - identifier: blog
    name: Blog
    url: blog
    pre: blog.svg
    weight: 4
  - identifier: contact
    name: Contact
    url: contact
    pre: contact.svg
    weight: 5